### ISSUE TITLE
.gitconfig location

### ISSUE THREAD

**Issue by tenhobi** [HugoGiraudel/dotfiles#1]
Hello, is there any working way how you use `.gitconfig` at your repository level, so you can push/pull it? I mean something like `repository/.gitconfig`.

**Comment by tenhobi** [comment]
W/O set some path to the file from anywhere. I want something what I pull and it can works. :smirk_cat:

**Comment by KittyGiraudel** [comment]
To be perfectly honest I am not even sure it is possible to use `.gitconfig` on a repository basis. If there is a way I don't know it. I'm sorry. :(

**Comment by tenhobi** [comment]
Everyone writes that you can use only 3 places: `--system`, `--global`, `--local`. So you can use `--local` but that is in `.git/config` file, so it is not a part of repository. 

Maybe I can write some shell with commands like `git config --local alias.co checkout` which I call after my pull...

**Comment by KittyGiraudel** [comment]
Perhaps have a Google search or a Twitter question about this, 'cause I don't know. :(

**Comment by tenhobi** [comment]
I have found you can only have it in 3 places as I wrote above.

I wrote a script which connect me the .gitignore with local path. 
https://github.com/HoBi/config
